import React, { useState, useEffect } from 'react';
import { CCTVCamera, IncidentRecord, SIHScenarioPreset, CCTVAnalysisResult } from './types';
import { INITIAL_CAMERAS, SIH_SCENARIOS } from './data/cctvFeeds';
import { HeaderNav } from './components/HeaderNav';
import { LiveCctvGrid } from './components/LiveCctvGrid';
import { CctvCanvasStream } from './components/CctvCanvasStream';
import { EscalationEngine } from './components/EscalationEngine';
import { AiVisionInspector } from './components/AiVisionInspector';
import { CampusMapView } from './components/CampusMapView';
import { AnalyticsDashboard } from './components/AnalyticsDashboard';
import { SihDemoGuideModal } from './components/SihDemoGuideModal';
import { 
  ShieldAlert, 
  Eye, 
  MapPin, 
  Clock, 
  SunMedium, 
  Users, 
  Radio, 
  Zap, 
  Sparkles, 
  Layers,
  ArrowLeft
} from 'lucide-react';

export default function App() {
  const [cameras, setCameras] = useState<CCTVCamera[]>(INITIAL_CAMERAS);
  const [selectedCamera, setSelectedCamera] = useState<CCTVCamera>(INITIAL_CAMERAS[0]);
  const [activeTab, setActiveTab] = useState<'grid' | 'inspector' | 'map' | 'analytics'>('grid');
  const [isInfoModalOpen, setIsInfoModalOpen] = useState<boolean>(false);
  const [spotlightActive, setSpotlightActive] = useState<boolean>(false);
  const [isSimpleMode, setIsSimpleMode] = useState<boolean>(true);
  const [showHowItWorksBanner, setShowHowItWorksBanner] = useState<boolean>(true);

  // Incidents Ledger History
  const [incidents, setIncidents] = useState<IncidentRecord[]>([
    {
      id: 'INC-904211',
      timestamp: '01:45:20 AM',
      cameraId: 'cam-01',
      cameraName: 'Girls Hostel North Pathway',
      location: 'Hostel Sector North',
      threatLevel: 'CRITICAL_DANGER',
      threatScore: 88,
      genderRatio: '1 Female : 2 Males (Skewed Isolated)',
      detectedBehaviors: ['Direct Trailing & Rapid Acceleration', 'Blocking Egress Corner'],
      ambientLux: 18,
      stage: 'STAGE_1_WARNING',
    },
    {
      id: 'INC-904185',
      timestamp: '22:40:12 PM',
      cameraId: 'cam-04',
      cameraName: 'Basement Parking Lot B (Pillar 14)',
      location: 'Vehicle & Logistics Sector',
      threatLevel: 'CRITICAL_DANGER',
      threatScore: 84,
      genderRatio: '1 Female : 2 Males',
      detectedBehaviors: ['Pillar Concealment & Cornering'],
      ambientLux: 22,
      stage: 'STAGE_4_ESCALATED_POLICE',
      dispatchedAt: '22:40:42 PM',
      dispatchUnits: [
        { unitId: 'PCR-09', agency: 'Police Flying Squad', eta: '3 mins', contact: '+91 112' },
        { unitId: 'QRT-02', agency: 'Campus Rapid Reaction', eta: '45 secs', contact: 'VHF-4' },
      ],
      operatorNotes: 'Fail-safe timeout elapsed; Police unit confirmed on scene.',
    },
    {
      id: 'INC-903950',
      timestamp: '20:15:08 PM',
      cameraId: 'cam-06',
      cameraName: 'Cafeteria Rear Loading Dock',
      location: 'Commercial & Dining',
      threatLevel: 'SUSPICIOUS',
      threatScore: 48,
      genderRatio: '2 Females : 4 Males',
      detectedBehaviors: ['Clustered Loitering'],
      ambientLux: 65,
      stage: 'ACKNOWLEDGED',
      acknowledgedBy: 'Officer Sharma (Ext 4099)',
      acknowledgedAt: '20:15:35 PM',
      operatorNotes: 'Staff unloading kitchen supplies.',
    },
  ]);

  // Compute active threats count (critical & elevated)
  const activeThreatCount = cameras.filter(
    (c) => c.defaultThreatLevel === 'CRITICAL_DANGER' || c.defaultThreatLevel === 'THREAT_ELEVATED'
  ).length;

  // Apply SIH Scenario Preset
  const handleApplyScenario = (scenario: SIHScenarioPreset) => {
    const targetCam = cameras.find((c) => c.id === scenario.cameraId);
    if (targetCam) {
      setSelectedCamera(targetCam);
      // Switch view if in grid or inspector
    }
  };

  // Handle new incident generated by escalation engine or inspector
  const handleDispatchUpdate = (newIncident: IncidentRecord) => {
    setIncidents((prev) => [newIncident, ...prev.filter((i) => i.id !== newIncident.id)]);
  };

  // Handle Gemini analysis results from Inspector
  const handleAnalysisComplete = (res: CCTVAnalysisResult) => {
    setCameras((prev) =>
      prev.map((c) =>
        c.id === selectedCamera.id
          ? {
              ...c,
              defaultThreatLevel: res.threatLevel,
              defaultThreatScore: res.threatScore,
              defaultAnalysis: res,
            }
          : c
      )
    );

    setSelectedCamera((prev) => ({
      ...prev,
      defaultThreatLevel: res.threatLevel,
      defaultThreatScore: res.threatScore,
      defaultAnalysis: res,
    }));
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col selection:bg-rose-500 selection:text-white font-sans antialiased">
      {/* Top Navigation Bar */}
      <HeaderNav
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        activeThreatCount={activeThreatCount}
        onOpenInfoModal={() => setIsInfoModalOpen(true)}
        isSimpleMode={isSimpleMode}
        onToggleSimpleMode={() => setIsSimpleMode((prev) => !prev)}
      />

      {/* Main Content Body */}
      <main className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6 lg:p-8 flex flex-col gap-6">
        {/* Friendly "How It Works" 3-Step Quick Guide Banner */}
        {showHowItWorksBanner && (
          <div className="relative p-4 sm:p-5 rounded-2xl bg-gradient-to-r from-slate-900 via-slate-900/95 to-slate-950 border border-slate-800 shadow-xl overflow-hidden">
            <div className="flex items-start justify-between gap-4 pb-3 border-b border-slate-800/80">
              <div className="flex items-center gap-2.5">
                <div className="p-1.5 rounded-lg bg-rose-500/20 text-rose-300 border border-rose-500/30">
                  <Sparkles className="w-4 h-4" />
                </div>
                <div>
                  <h2 className="text-sm sm:text-base font-bold text-slate-100 flex items-center gap-2">
                    <span>How NirbhayaVision Women Safety AI Works</span>
                    <span className="text-[11px] px-2 py-0.5 rounded-full bg-emerald-950 text-emerald-300 border border-emerald-800 font-normal">
                      Instant Overview
                    </span>
                  </h2>
                  <p className="text-xs text-slate-400">
                    Continuous multi-factor CCTV analytics that protects female students in isolated areas.
                  </p>
                </div>
              </div>

              <button
                onClick={() => setShowHowItWorksBanner(false)}
                className="text-xs text-slate-400 hover:text-slate-200 px-2 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 transition-all"
                title="Hide this guide banner"
              >
                Dismiss Guide ✕
              </button>
            </div>

            {/* 3 Simple Visual Steps */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pt-3">
              {/* Step 1 */}
              <div className="p-3 rounded-xl bg-slate-950/70 border border-slate-800/90 flex flex-col gap-1.5">
                <div className="flex items-center gap-2 text-xs font-bold text-slate-200">
                  <span className="w-5 h-5 rounded-full bg-pink-500/20 text-pink-400 border border-pink-500/40 flex items-center justify-center font-mono text-[11px]">
                    1
                  </span>
                  <span>Colored Dot Person Tracking</span>
                </div>
                <p className="text-[11px] text-slate-400 leading-relaxed">
                  The AI identifies individuals with colored dots: <strong className="text-pink-400 font-bold">♀ Pink Dot = Female</strong> and <strong className="text-sky-400 font-bold">♂ Blue Dot = Male</strong>.
                </p>
              </div>

              {/* Step 2 */}
              <div className="p-3 rounded-xl bg-slate-950/70 border border-slate-800/90 flex flex-col gap-1.5">
                <div className="flex items-center gap-2 text-xs font-bold text-slate-200">
                  <span className="w-5 h-5 rounded-full bg-amber-500/20 text-amber-400 border border-amber-500/40 flex items-center justify-center font-mono text-[11px]">
                    2
                  </span>
                  <span>Multi-Risk AI Assessment</span>
                </div>
                <p className="text-[11px] text-slate-400 leading-relaxed">
                  Measures darkness (<strong className="text-amber-300">Lux</strong>), loneliness/isolation, walking velocity, and aggressive trailing behind a female subject.
                </p>
              </div>

              {/* Step 3 */}
              <div className="p-3 rounded-xl bg-slate-950/70 border border-slate-800/90 flex flex-col gap-1.5">
                <div className="flex items-center gap-2 text-xs font-bold text-slate-200">
                  <span className="w-5 h-5 rounded-full bg-rose-500/20 text-rose-400 border border-rose-500/40 flex items-center justify-center font-mono text-[11px]">
                    3
                  </span>
                  <span>Fail-Safe Police 112 Dispatch</span>
                </div>
                <p className="text-[11px] text-slate-400 leading-relaxed">
                  If danger is detected, a 30s timer starts. If the operator misses it or is away, the system <strong className="text-rose-300">automatically calls Police 112</strong>!
                </p>
              </div>
            </div>

            {/* Quick Demo Test Buttons */}
            <div className="mt-3 pt-3 border-t border-slate-800/70 flex items-center justify-between flex-wrap gap-2">
              <span className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
                <Zap className="w-3.5 h-3.5 text-amber-400" />
                Try Interactive Scenarios:
              </span>
              <div className="flex items-center gap-2 flex-wrap">
                {SIH_SCENARIOS.map((sc) => {
                  const isCurrent = selectedCamera.id === sc.cameraId;
                  return (
                    <button
                      key={sc.id}
                      onClick={() => handleApplyScenario(sc)}
                      className={`px-2.5 py-1 rounded-lg text-xs font-medium border transition-all ${
                        isCurrent
                          ? 'bg-rose-600 text-white border-rose-500 shadow-md font-bold'
                          : 'bg-slate-800/90 hover:bg-slate-700 text-slate-300 border-slate-700'
                      }`}
                    >
                      {sc.title}
                    </button>
                  );
                })}
              </div>
            </div>
          </div>
        )}

        {/* TAB 1: LIVE CCTV GRID VIEW */}
        {activeTab === 'grid' && (
          <div className="flex flex-col gap-6">
            {/* Split View: Primary Focused Camera with Live Fail-Safe Panel */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
              {/* Primary Large Canvas Stream (7 Cols) */}
              <div className="lg:col-span-7 flex flex-col gap-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="w-2.5 h-2.5 rounded-full bg-rose-500 animate-ping" />
                    <span className="text-xs font-bold text-slate-200">
                      Live Video Stream — {selectedCamera.name} ({selectedCamera.code})
                    </span>
                  </div>
                  <button
                    onClick={() => setActiveTab('inspector')}
                    className="px-2.5 py-1 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-800 text-xs font-medium text-sky-400 flex items-center gap-1 transition-all"
                  >
                    <Eye className="w-3.5 h-3.5" />
                    <span>Deep AI Scan</span>
                  </button>
                </div>

                <div className="aspect-[16/10] w-full">
                  <CctvCanvasStream
                    camera={selectedCamera}
                    spotlightActive={spotlightActive}
                    showBoundingBoxes={true}
                    onCaptureFrame={(dataUrl) => {
                      setActiveTab('inspector');
                    }}
                  />
                </div>

                {/* Friendly Visual Dot Legend & Telemetry Bar */}
                <div className="p-3.5 rounded-2xl bg-slate-900/90 border border-slate-800 flex flex-col gap-2">
                  {/* Visual Color Dot Legend */}
                  <div className="flex items-center justify-between flex-wrap gap-2 text-xs pb-2 border-b border-slate-800/80">
                    <span className="font-semibold text-slate-400">Color Dot Legend:</span>
                    <div className="flex items-center gap-3">
                      <div className="flex items-center gap-1.5">
                        <span className="w-3 h-3 rounded-full bg-pink-500 ring-2 ring-pink-500/30" />
                        <span className="text-pink-300 font-bold">♀ Female Subject</span>
                      </div>
                      <div className="flex items-center gap-1.5">
                        <span className="w-3 h-3 rounded-full bg-sky-500 ring-2 ring-sky-500/30" />
                        <span className="text-sky-300 font-bold">♂ Male Entity</span>
                      </div>
                      <div className="flex items-center gap-1.5">
                        <span className="w-3 h-3 rounded-full bg-amber-500 ring-2 ring-amber-500/30" />
                        <span className="text-amber-300 font-bold">⚠️ Stalker Trailing</span>
                      </div>
                    </div>
                  </div>

                  {/* Telemetry metrics */}
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
                    <div className="flex items-center gap-1.5 text-slate-300">
                      <MapPin className="w-3.5 h-3.5 text-rose-400" />
                      <span className="truncate">{selectedCamera.zone}</span>
                    </div>
                    <div className="flex items-center gap-1.5 text-slate-300">
                      <Clock className="w-3.5 h-3.5 text-sky-400" />
                      <span>{selectedCamera.timeOfDay}</span>
                    </div>
                    <div className="flex items-center gap-1.5 text-slate-300">
                      <SunMedium className="w-3.5 h-3.5 text-amber-400" />
                      <span>{selectedCamera.ambientLux} Lux ({selectedCamera.ambientLux < 30 ? 'Dark' : 'Lit'})</span>
                    </div>
                    <div className="flex items-center gap-1.5 text-slate-300">
                      <Users className="w-3.5 h-3.5 text-indigo-400" />
                      <span>{selectedCamera.defaultAnalysis.genderDistribution.femaleCount} Female : {selectedCamera.defaultAnalysis.genderDistribution.maleCount} Male</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Fail-Safe Escalation Engine (5 Cols) */}
              <div className="lg:col-span-5 flex flex-col">
                <EscalationEngine
                  activeCamera={selectedCamera}
                  onDispatchUpdate={handleDispatchUpdate}
                  onToggleSpotlight={(val) => setSpotlightActive(val)}
                />
              </div>
            </div>

            {/* 6-Camera Multi-Feed Grid */}
            <div className="pt-4 border-t border-slate-800/80">
              <LiveCctvGrid
                cameras={cameras}
                selectedCamera={selectedCamera}
                onSelectCamera={(cam) => setSelectedCamera(cam)}
                onApplyScenario={handleApplyScenario}
                spotlightActive={spotlightActive}
              />
            </div>
          </div>
        )}

        {/* TAB 2: AI VISION & SITUATIONAL INSPECTOR VIEW */}
        {activeTab === 'inspector' && (
          <div className="flex flex-col gap-6">
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
              {/* Left Live Canvas (5 Cols) */}
              <div className="lg:col-span-5 flex flex-col gap-3">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-mono font-bold text-slate-300">
                    OPTICAL TARGET // {selectedCamera.code}
                  </span>
                  <select
                    value={selectedCamera.id}
                    onChange={(e) => {
                      const found = cameras.find((c) => c.id === e.target.value);
                      if (found) setSelectedCamera(found);
                    }}
                    className="bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 text-xs text-slate-200"
                  >
                    {cameras.map((c) => (
                      <option key={c.id} value={c.id}>
                        {c.code} - {c.name}
                      </option>
                    ))}
                  </select>
                </div>

                <div className="aspect-[16/10] w-full">
                  <CctvCanvasStream
                    camera={selectedCamera}
                    spotlightActive={spotlightActive}
                    showBoundingBoxes={true}
                  />
                </div>

                {/* Camera Profile Info */}
                <div className="p-4 rounded-xl bg-slate-900/90 border border-slate-800 text-xs space-y-2">
                  <div className="font-bold text-slate-200">{selectedCamera.name}</div>
                  <p className="text-slate-400 text-[11px]">{selectedCamera.locationDetails}</p>
                  <div className="pt-2 border-t border-slate-800 font-mono text-[11px] text-slate-300 space-y-1">
                    <div>Nearest Sentry: <strong>{selectedCamera.nearestGuardPost}</strong> ({selectedCamera.nearestGuardDistanceMeters}m)</div>
                    <div>Isolation Profile: <strong className="text-rose-300">{selectedCamera.isolationLevel}</strong></div>
                  </div>
                </div>
              </div>

              {/* Right Deep AI Inspector (7 Cols) */}
              <div className="lg:col-span-7">
                <AiVisionInspector
                  camera={selectedCamera}
                  onAnalysisComplete={handleAnalysisComplete}
                  latestAnalysis={selectedCamera.defaultAnalysis}
                />
              </div>
            </div>
          </div>
        )}

        {/* TAB 3: CAMPUS TACTICAL MAP VIEW */}
        {activeTab === 'map' && (
          <div className="flex flex-col gap-6">
            <CampusMapView
              cameras={cameras}
              selectedCamera={selectedCamera}
              onSelectCamera={(cam) => {
                setSelectedCamera(cam);
              }}
            />
          </div>
        )}

        {/* TAB 4: ANALYTICS & INCIDENT LOGS VIEW */}
        {activeTab === 'analytics' && (
          <div className="flex flex-col gap-6">
            <AnalyticsDashboard incidents={incidents} />
          </div>
        )}
      </main>

      {/* SIH 2026 Submission & Evaluation Guide Modal */}
      <SihDemoGuideModal
        isOpen={isInfoModalOpen}
        onClose={() => setIsInfoModalOpen(false)}
      />

      {/* Footer Bar */}
      <footer className="mt-auto border-t border-slate-800/80 bg-slate-950/80 px-4 py-3 text-center text-xs font-mono text-slate-500">
        NirbhayaVision AI Core • Smart India Hackathon (SIH) 2026 • Real-Time Fail-Safe Women Safety Analytics Surveillance
      </footer>
    </div>
  );
}
